#!/usr/bin/env python3
"""
generate_svg_header.py
======================
Reads all status_*.svg files from the svg/ directory and writes
PrintStatusIconSVG.hpp — a header containing the SVG strings as
inline C++ string literals, mapped to PrintState enum values.

Run this from the orca_status_icons/ directory:
    python3 generate_svg_header.py

The output file goes into src/PrintStatusIconSVG.hpp.
Re-run whenever you edit an SVG.
"""

import os
import re

SVG_DIR    = os.path.join(os.path.dirname(__file__), "svg")
OUTPUT     = os.path.join(os.path.dirname(__file__), "src", "PrintStatusIconSVG.hpp")

# Maps filename stem → PrintState enum value
STATE_MAP = {
    "status_idle":            "PrintState::IDLE",
    "status_slicing":         "PrintState::SLICING",
    "status_sliced":          "PrintState::SLICED",
    "status_sending":         "PrintState::SENDING",
    "status_prepare":         "PrintState::PREPARE",
    "status_running":         "PrintState::RUNNING",
    "status_pause":           "PrintState::PAUSE",
    "status_filament_change": "PrintState::FILAMENT_CHANGE",
    "status_calibrating":     "PrintState::CALIBRATING",
    "status_finish":          "PrintState::FINISH",
    "status_failed":          "PrintState::FAILED",
    "status_offline":         "PrintState::OFFLINE",
}

def escape_cpp_string(s: str) -> str:
    """Escape a string for use inside a C++ raw string literal (R"SVG(...)SVG")."""
    # Raw string literals can't contain the delimiter sequence )SVG"
    # These icons don't use that sequence, but we replace it just in case.
    return s.replace(')SVG"', ')_SVG"')

def main():
    entries: list[tuple[str, str]] = []   # (enum_value, svg_content)

    for filename in sorted(os.listdir(SVG_DIR)):
        if not filename.endswith(".svg"):
            continue
        stem = filename[:-4]
        if stem not in STATE_MAP:
            print(f"  WARNING: {filename} has no STATE_MAP entry — skipped")
            continue
        path = os.path.join(SVG_DIR, filename)
        with open(path, "r", encoding="utf-8") as f:
            content = f.read().strip()
        entries.append((STATE_MAP[stem], escape_cpp_string(content)))
        print(f"  Embedded {filename} → {STATE_MAP[stem]}")

    lines = [
        "// PrintStatusIconSVG.hpp — AUTO-GENERATED by generate_svg_header.py",
        "// Do NOT edit manually.  Run the script to regenerate.",
        "#pragma once",
        "#include \"PrintStatusIcon.hpp\"",
        "#include <unordered_map>",
        "#include <string>",
        "",
        "namespace Slic3r {",
        "namespace GUI {",
        "namespace PrintStatusIconSVG {",
        "",
        "inline wxString Get(PrintState state)",
        "{",
        "    // Lazy-init map of state → SVG string.",
        "    static const std::unordered_map<int, wxString> kSVGs = {",
    ]

    for enum_val, svg in entries:
        # Use a raw string literal to avoid escaping every quote in the SVG.
        lines.append(f"        {{ static_cast<int>({enum_val}), wxString::FromUTF8(R\"SVG(")
        lines.append(svg)
        lines.append(")SVG\") },")

    lines += [
        "    };",
        "",
        "    auto it = kSVGs.find(static_cast<int>(state));",
        "    if (it != kSVGs.end())",
        "        return it->second;",
        "    return kSVGs.at(static_cast<int>(PrintState::IDLE));",
        "}",
        "",
        "} // namespace PrintStatusIconSVG",
        "} // namespace GUI",
        "} // namespace Slic3r",
    ]

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nWrote {OUTPUT} ({len(entries)} states embedded)")

if __name__ == "__main__":
    main()
