// PrintStatusIconSVG.hpp — AUTO-GENERATED by generate_svg_header.py 
// script is located in .../resources/images/print_status/generate_svg_header.py
// Do NOT edit manually.  Run the script to regenerate.
#pragma once
#include "PrintStatusIcon.hpp"
#include <unordered_map>
#include <string>

namespace Slic3r {
namespace GUI {
namespace PrintStatusIconSVG {

inline wxString Get(PrintState state)
{
    // Lazy-init map of state → SVG string.
    static const std::unordered_map<int, wxString> kSVGs = {
        { static_cast<int>(PrintState::CALIBRATING), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes spin     { to { transform: rotate(360deg);  } }
    @keyframes spin-ccw { to { transform: rotate(-360deg); } }
    .cal-cross  { animation: spin     3s linear infinite; transform-origin: 36px 36px; }
    .cal-dots   { animation: spin-ccw 2s linear infinite; transform-origin: 36px 36px; }
    @media (prefers-reduced-motion: reduce) {
      .cal-cross, .cal-dots { animation: none; }
    }
  </style>
  <!-- Outer dashed ring -->
  <circle cx="36" cy="36" r="22"
    fill="none" stroke="#888780" stroke-width="1" stroke-dasharray="2 4"/>
  <!-- Rotating cross/crosshair -->
  <g class="cal-cross">
    <line x1="36" y1="14" x2="36" y2="58" stroke="#5F5E5A" stroke-width="1.5" stroke-linecap="round"/>
    <line x1="14" y1="36" x2="58" y2="36" stroke="#5F5E5A" stroke-width="1.5" stroke-linecap="round"/>
    <line x1="20" y1="20" x2="52" y2="52" stroke="#5F5E5A" stroke-width="1"   stroke-linecap="round" opacity="0.5"/>
    <line x1="52" y1="20" x2="20" y2="52" stroke="#5F5E5A" stroke-width="1"   stroke-linecap="round" opacity="0.5"/>
  </g>
  <!-- CCW orbiting dots -->
  <g class="cal-dots">
    <circle cx="36" cy="14" r="2.5" fill="#B4B2A9"/>
    <circle cx="58" cy="36" r="2.5" fill="#B4B2A9"/>
    <circle cx="36" cy="58" r="2.5" fill="#B4B2A9"/>
    <circle cx="14" cy="36" r="2.5" fill="#B4B2A9"/>
  </g>
  <!-- Target center -->
  <circle cx="36" cy="36" r="8" fill="#F1EFE8" stroke="#888780" stroke-width="1"/>
  <circle cx="36" cy="36" r="4" fill="#D3D1C7" stroke="#5F5E5A" stroke-width="0.8"/>
  <!-- Axolotl eyes inside target -->
  <circle cx="34.5" cy="35" r="1" fill="#2C2C2A"/>
  <circle cx="37.5" cy="35" r="1" fill="#2C2C2A"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::FAILED), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.3} }
    .tear { animation: pulse 2s ease-in-out infinite; }
    .tear2 { animation: pulse 2s ease-in-out infinite 0.5s; }
    @media (prefers-reduced-motion: reduce) { .tear, .tear2 { animation: none; } }
  </style>
  <!-- Warning triangle -->
  <polygon points="36,10 58,48 14,48"
    fill="#FCEBEB" stroke="#A32D2D" stroke-width="1.5"/>
  <!-- X mark -->
  <line x1="28" y1="28" x2="44" y2="44"
    stroke="#E24B4A" stroke-width="2.5" stroke-linecap="round"/>
  <line x1="44" y1="28" x2="28" y2="44"
    stroke="#E24B4A" stroke-width="2.5" stroke-linecap="round"/>
  <!-- Sad axolotl at bottom -->
  <circle cx="36" cy="54" r="6" fill="#FCEBEB" stroke="#A32D2D" stroke-width="1"/>
  <circle cx="34" cy="53" r="1.2" fill="#791F1F"/>
  <circle cx="38" cy="53" r="1.2" fill="#791F1F"/>
  <!-- Sad frown -->
  <path d="M33 57 Q36 55 39 57"
    fill="none" stroke="#791F1F" stroke-width="1" stroke-linecap="round"/>
  <!-- Tear drops -->
  <ellipse class="tear"  cx="33" cy="59" rx="1" ry="1.5" fill="#F7C1C1"/>
  <ellipse class="tear2" cx="39" cy="59" rx="1" ry="1.5" fill="#F7C1C1"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::FILAMENT_CHANGE), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes spin { to { transform: rotate(360deg); } }
    .spool-spin {
      animation: spin 4s linear infinite;
      transform-origin: 36px 36px;
    }
    @media (prefers-reduced-motion: reduce) { .spool-spin { animation: none; } }
  </style>
  <defs>
    <marker id="arrowhead" viewBox="0 0 10 10" refX="8" refY="5"
      markerWidth="5" markerHeight="5" orient="auto-start-reverse">
      <path d="M2 1L8 5L2 9" fill="none" stroke="#534AB7"
        stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
    </marker>
  </defs>
  <!-- Outer spool ring -->
  <circle cx="36" cy="36" r="20"
    fill="none" stroke="#534AB7" stroke-width="1.5"/>
  <!-- Inner hub -->
  <circle cx="36" cy="36" r="8"
    fill="none" stroke="#534AB7" stroke-width="1"/>
  <!-- Spinning filament strands -->
  <g class="spool-spin">
    <path d="M36 16 Q50 20 56 36 Q50 52 36 56 Q22 52 16 36 Q22 20 36 16"
      fill="none" stroke="#7F77DD" stroke-width="2" stroke-dasharray="6 3"/>
  </g>
  <!-- Axolotl face in hub -->
  <circle cx="36" cy="36" r="5" fill="#EEEDFE" stroke="#534AB7" stroke-width="0.8"/>
  <circle cx="34" cy="35" r="1"   fill="#3C3489"/>
  <circle cx="38" cy="35" r="1"   fill="#3C3489"/>
  <path d="M34 38 Q36 40 38 38"
    fill="none" stroke="#3C3489" stroke-width="0.8" stroke-linecap="round"/>
  <!-- Color-change arrows -->
  <path d="M22 20 L28 26"
    fill="none" stroke="#534AB7" stroke-width="1.5"
    stroke-linecap="round" marker-end="url(#arrowhead)"/>
  <path d="M50 20 L44 26"
    fill="none" stroke="#D85A30" stroke-width="1.5"
    stroke-linecap="round"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::FINISH), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes pulse-scale {
      0%,100% { transform: scale(1); }
      50%      { transform: scale(1.1); }
    }
    @keyframes ring-expand {
      0%   { r: 8;  opacity: 0.7; }
      100% { r: 30; opacity: 0; }
    }
    .star-burst   { animation: pulse-scale 2s ease-in-out infinite; transform-origin: 36px 36px; }
    .finish-ring  { animation: ring-expand 2s ease-out infinite; }
    @media (prefers-reduced-motion: reduce) {
      .star-burst, .finish-ring { animation: none; }
    }
  </style>
  <!-- Starburst celebration -->
  <g class="star-burst">
    <polygon
      points="36,12 39,28 54,24 44,36 58,44 42,44 44,60 36,48 28,60 30,44 14,44 28,36 18,24 33,28"
      fill="#9FE1CB" stroke="#1D9E75" stroke-width="0.5" opacity="0.7"/>
  </g>
  <!-- Completed part layers on bed -->
  <rect x="22" y="44" width="28" height="8" rx="2" fill="#5DCAA5" stroke="#0F6E56" stroke-width="0.8"/>
  <rect x="26" y="36" width="20" height="8" rx="1" fill="#5DCAA5" stroke="#0F6E56" stroke-width="0.8"/>
  <rect x="29" y="30" width="14" height="6" rx="1" fill="#5DCAA5" stroke="#0F6E56" stroke-width="0.8"/>
  <!-- Axolotl cheering on top -->
  <circle cx="36" cy="24" r="6" fill="#E1F5EE" stroke="#1D9E75" stroke-width="1"/>
  <circle cx="34" cy="23" r="1.2" fill="#085041"/>
  <circle cx="38" cy="23" r="1.2" fill="#085041"/>
  <!-- Big smile -->
  <path d="M33 26 Q36 30 39 26"
    fill="none" stroke="#085041" stroke-width="1" stroke-linecap="round"/>
  <!-- Arms raised -->
  <line x1="30" y1="24" x2="24" y2="18" stroke="#5DCAA5" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="42" y1="24" x2="48" y2="18" stroke="#5DCAA5" stroke-width="1.5" stroke-linecap="round"/>
  <!-- Expanding ring -->
  <circle class="finish-ring"
    cx="36" cy="36" r="8" fill="none" stroke="#5DCAA5" stroke-width="1"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::IDLE), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.4} }
    .idle-dot { animation: pulse 2.5s ease-in-out infinite; }
    @media (prefers-reduced-motion: reduce) { .idle-dot { animation: none; } }
  </style>
  <!-- Hexagonal frame -->
  <polygon points="36,14 50,24 50,48 36,58 22,48 22,24"
    fill="none" stroke="#7F77DD" stroke-width="1.5"/>
  <!-- Axolotl body -->
  <circle cx="36" cy="36" r="10" fill="#EEEDFE" stroke="#7F77DD" stroke-width="1"/>
  <!-- Eyes -->
  <circle cx="33" cy="34" r="2" fill="#534AB7"/>
  <circle cx="39" cy="34" r="2" fill="#534AB7"/>
  <!-- Gills -->
  <line x1="22" y1="24" x2="15" y2="18" stroke="#AFA9EC" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="22" y1="28" x2="14" y2="24" stroke="#AFA9EC" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="50" y1="24" x2="57" y2="18" stroke="#AFA9EC" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="50" y1="28" x2="58" y2="24" stroke="#AFA9EC" stroke-width="1.5" stroke-linecap="round"/>
  <!-- Smile -->
  <path d="M32 39 Q36 43 40 39" fill="none" stroke="#534AB7" stroke-width="1" stroke-linecap="round"/>
  <!-- Idle pulse dot -->
  <circle class="idle-dot" cx="36" cy="56" r="3" fill="#AFA9EC"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::OFFLINE), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.3} }
    .zzz1 { animation: pulse 2s ease-in-out infinite 0.0s; }
    .zzz2 { animation: pulse 2s ease-in-out infinite 0.5s; }
    .zzz3 { animation: pulse 2s ease-in-out infinite 1.0s; }
    @media (prefers-reduced-motion: reduce) {
      .zzz1, .zzz2, .zzz3 { animation: none; }
    }
  </style>
  <!-- Dashed hexagon = unavailable -->
  <polygon points="36,10 56,22 56,50 36,62 16,50 16,22"
    fill="none" stroke="#B4B2A9" stroke-width="1.5" stroke-dasharray="4 4"/>
  <!-- Faded wifi/signal arcs -->
  <path d="M24 40 Q36 28 48 40"
    fill="none" stroke="#D3D1C7" stroke-width="1.5" stroke-linecap="round"/>
  <path d="M28 44 Q36 36 44 44"
    fill="none" stroke="#B4B2A9" stroke-width="1.5" stroke-linecap="round"/>
  <!-- X over signal -->
  <line x1="28" y1="28" x2="44" y2="44"
    stroke="#888780" stroke-width="2" stroke-linecap="round"/>
  <line x1="44" y1="28" x2="28" y2="44"
    stroke="#888780" stroke-width="2" stroke-linecap="round"/>
  <!-- Sleeping axolotl -->
  <circle cx="36" cy="56" r="5" fill="#F1EFE8" stroke="#B4B2A9" stroke-width="0.8"/>
  <!-- Closed eyes -->
  <path d="M33 55 Q34 54 35 55" fill="none" stroke="#5F5E5A" stroke-width="0.8" stroke-linecap="round"/>
  <path d="M37 55 Q38 54 39 55" fill="none" stroke="#5F5E5A" stroke-width="0.8" stroke-linecap="round"/>
  <!-- Z z z -->
  <text class="zzz1" x="44" y="52" font-size="8"  fill="#B4B2A9" font-family="sans-serif" font-weight="500">z</text>
  <text class="zzz2" x="48" y="46" font-size="10" fill="#D3D1C7" font-family="sans-serif" font-weight="500">z</text>
  <text class="zzz3" x="53" y="39" font-size="12" fill="#D3D1C7" font-family="sans-serif" font-weight="500">z</text>
</svg>
)SVG") },
        { static_cast<int>(PrintState::PAUSE), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes pulse-ring { 0%,100%{opacity:0.6; r:10} 50%{opacity:0.2; r:14} }
    .pause-ring { animation: pulse-ring 2s ease-in-out infinite; }
    @media (prefers-reduced-motion: reduce) { .pause-ring { animation: none; } }
  </style>
  <!-- Hexagonal frame amber -->
  <polygon points="36,10 56,22 56,50 36,62 16,50 16,22"
    fill="#FAEEDA" stroke="#BA7517" stroke-width="1.5"/>
  <!-- Pause bars -->
  <rect x="27" y="27" width="6" height="18" rx="2" fill="#EF9F27"/>
  <rect x="39" y="27" width="6" height="18" rx="2" fill="#EF9F27"/>
  <!-- Axolotl face: worried expression -->
  <circle cx="33" cy="24" r="1.5" fill="#854F0B"/>
  <circle cx="39" cy="24" r="1.5" fill="#854F0B"/>
  <!-- Furrowed brow lines -->
  <line x1="31" y1="21" x2="35" y2="22" stroke="#854F0B" stroke-width="0.8"/>
  <line x1="37" y1="22" x2="41" y2="21" stroke="#854F0B" stroke-width="0.8"/>
  <!-- Flat mouth -->
  <line x1="33" y1="26" x2="39" y2="26"
    stroke="#854F0B" stroke-width="0.8" stroke-linecap="round"/>
  <!-- Gills -->
  <line x1="16" y1="30" x2="9"  y2="24" stroke="#FAC775" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="56" y1="30" x2="63" y2="24" stroke="#FAC775" stroke-width="1.5" stroke-linecap="round"/>
  <!-- Pulsing ring -->
  <circle class="pause-ring"
    cx="36" cy="36" r="10" fill="none" stroke="#EF9F27" stroke-width="0.8"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::PREPARE), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.3} }
    .heat-pulse { animation: pulse 1.5s ease-in-out infinite; }
    @media (prefers-reduced-motion: reduce) { .heat-pulse { animation: none; } }
  </style>
  <!-- Dashed outer ring -->
  <circle cx="36" cy="36" r="22"
    fill="none" stroke="#BA7517" stroke-width="1" stroke-dasharray="3 4"/>
  <!-- Outer triangle -->
  <polygon points="36,20 48,42 24,42"
    fill="none" stroke="#EF9F27" stroke-width="1.5"/>
  <!-- Inner triangle fill -->
  <polygon points="36,26 44,40 28,40"
    fill="#FAEEDA" stroke="#EF9F27" stroke-width="1"/>
  <!-- Thermometer body -->
  <rect x="33" y="28" width="6" height="12" rx="3"
    fill="none" stroke="#BA7517" stroke-width="1"/>
  <!-- Thermometer mercury - animates -->
  <rect class="heat-pulse"
    x="34.5" y="34" width="3" height="6" rx="1.5" fill="#EF9F27"/>
  <!-- Axolotl eyes -->
  <circle cx="32" cy="46" r="1.2" fill="#854F0B"/>
  <circle cx="40" cy="46" r="1.2" fill="#854F0B"/>
  <!-- Gills -->
  <line x1="24" y1="42" x2="18" y2="36" stroke="#FAC775" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="48" y1="42" x2="54" y2="36" stroke="#FAC775" stroke-width="1.5" stroke-linecap="round"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::RUNNING), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes bob { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-4px)} }
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.2} }
    @keyframes layer-rise {
      0%   { transform: translateY(0);  opacity: 0.6; }
      100% { transform: translateY(-6px); opacity: 0; }
    }
    .nozzle       { animation: bob 1.5s ease-in-out infinite; transform-origin: 36px 30px; }
    .extrude-dot  { animation: pulse 0.8s ease-in-out infinite; }
    .new-layer    { animation: layer-rise 2s ease-out infinite; transform-origin: 36px 36px; }
    @media (prefers-reduced-motion: reduce) {
      .nozzle, .extrude-dot, .new-layer { animation: none; }
    }
  </style>
  <!-- Hexagonal frame -->
  <polygon points="36,10 56,22 56,50 36,62 16,50 16,22"
    fill="none" stroke="#0F6E56" stroke-width="1.5"/>
  <!-- Completed layer stack -->
  <rect x="23" y="46" width="26" height="4" rx="1" fill="#5DCAA5"/>
  <rect x="23" y="40" width="26" height="4" rx="1" fill="#5DCAA5" opacity="0.8"/>
  <!-- Newest layer animating up -->
  <rect class="new-layer"
    x="23" y="34" width="20" height="4" rx="1" fill="#5DCAA5" opacity="0.6"/>
  <!-- Print nozzle with axolotl face -->
  <g class="nozzle">
    <polygon points="31,24 41,24 39,31 33,31" fill="#1D9E75"/>
    <circle cx="34" cy="26" r="1.2" fill="#085041"/>
    <circle cx="38" cy="26" r="1.2" fill="#085041"/>
  </g>
  <!-- Extrusion filament dot -->
  <circle class="extrude-dot"
    cx="36" cy="34" r="1.5" fill="#9FE1CB"/>
  <!-- Gills -->
  <line x1="16" y1="30" x2="9"  y2="24" stroke="#9FE1CB" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="16" y1="36" x2="8"  y2="34" stroke="#9FE1CB" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="56" y1="30" x2="63" y2="24" stroke="#9FE1CB" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="56" y1="36" x2="64" y2="34" stroke="#9FE1CB" stroke-width="1.5" stroke-linecap="round"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::SENDING), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes bob { 0%,100%{transform:translateY(0)} 50%{transform:translateY(-5px)} }
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:0.3} }
    .upload-arrow { animation: bob 1.2s ease-in-out infinite; }
    .dot1 { animation: pulse 1s ease-in-out infinite 0.0s; }
    .dot2 { animation: pulse 1s ease-in-out infinite 0.3s; }
    .dot3 { animation: pulse 1s ease-in-out infinite 0.6s; }
    @media (prefers-reduced-motion: reduce) {
      .upload-arrow, .dot1, .dot2, .dot3 { animation: none; }
    }
  </style>
  <!-- Diamond frame -->
  <polygon points="36,12 56,36 36,60 16,36"
    fill="none" stroke="#185FA5" stroke-width="1.5"/>
  <!-- Animated upload arrow group -->
  <g class="upload-arrow">
    <line x1="36" y1="46" x2="36" y2="26"
      stroke="#378ADD" stroke-width="2" stroke-linecap="round"/>
    <polyline points="29,34 36,26 43,34"
      fill="none" stroke="#378ADD" stroke-width="2"
      stroke-linecap="round" stroke-linejoin="round"/>
  </g>
  <!-- Progress dots -->
  <circle class="dot1" cx="28" cy="54" r="2.5" fill="#B5D4F4"/>
  <circle class="dot2" cx="36" cy="54" r="2.5" fill="#85B7EB"/>
  <circle class="dot3" cx="44" cy="54" r="2.5" fill="#378ADD"/>
  <!-- Axolotl eyes on diamond -->
  <circle cx="32" cy="34" r="1.5" fill="#185FA5"/>
  <circle cx="40" cy="34" r="1.5" fill="#185FA5"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::SLICED), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <!-- No animation needed - static success state -->
  <!-- Hexagonal frame filled green -->
  <polygon points="36,10 52,20 52,52 36,62 20,52 20,20"
    fill="#EAF3DE" stroke="#639922" stroke-width="1.5"/>
  <!-- Axolotl body -->
  <circle cx="36" cy="36" r="10" fill="#C0DD97" stroke="#639922" stroke-width="1"/>
  <!-- Eyes -->
  <circle cx="33" cy="34" r="1.8" fill="#3B6D11"/>
  <circle cx="39" cy="34" r="1.8" fill="#3B6D11"/>
  <!-- Smile -->
  <path d="M33 39 Q36 43 39 39" fill="none" stroke="#3B6D11" stroke-width="1.2" stroke-linecap="round"/>
  <!-- Large checkmark -->
  <path d="M26 36 L32 43 L46 28"
    fill="none" stroke="#3B6D11" stroke-width="2"
    stroke-linecap="round" stroke-linejoin="round"/>
  <!-- Gills -->
  <line x1="20" y1="28" x2="13" y2="22" stroke="#97C459" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="20" y1="33" x2="12" y2="30" stroke="#97C459" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="52" y1="28" x2="59" y2="22" stroke="#97C459" stroke-width="1.5" stroke-linecap="round"/>
  <line x1="52" y1="33" x2="60" y2="30" stroke="#97C459" stroke-width="1.5" stroke-linecap="round"/>
</svg>
)SVG") },
        { static_cast<int>(PrintState::SLICING), wxString::FromUTF8(R"SVG(
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 72 72">
  <style>
    @keyframes dash { to { stroke-dashoffset: -40; } }
    @keyframes scan { 0% { transform: translateY(0); } 100% { transform: translateY(22px); } }
    .spin-dash { animation: dash 1.5s linear infinite; }
    .scan-line { animation: scan 1.2s linear infinite; }
    @media (prefers-reduced-motion: reduce) {
      .spin-dash { animation: none; }
      .scan-line { animation: none; }
    }
  </style>
  <!-- Rotating dashed hexagon -->
  <polygon class="spin-dash"
    points="36,10 52,20 52,52 36,62 20,52 20,20"
    fill="none" stroke="#1D9E75" stroke-width="1" stroke-dasharray="5 3"/>
  <!-- Layer stack -->
  <rect x="24" y="44" width="24" height="4" rx="1" fill="#5DCAA5" opacity="0.9"/>
  <rect x="24" y="38" width="24" height="4" rx="1" fill="#5DCAA5" opacity="0.7"/>
  <rect x="24" y="32" width="24" height="4" rx="1" fill="#5DCAA5" opacity="0.5"/>
  <rect x="24" y="26" width="24" height="4" rx="1" fill="#5DCAA5" opacity="0.3"/>
  <!-- Scanning laser line -->
  <line class="scan-line"
    x1="18" y1="32" x2="54" y2="32"
    stroke="#1D9E75" stroke-width="1.5" stroke-linecap="round"/>
  <!-- Axolotl face on top frame -->
  <circle cx="36" cy="20" r="6" fill="#E1F5EE" stroke="#1D9E75" stroke-width="0.8"/>
  <circle cx="34" cy="19" r="1.2" fill="#0F6E56"/>
  <circle cx="38" cy="19" r="1.2" fill="#0F6E56"/>
  <path d="M34 22 Q36 24 38 22" fill="none" stroke="#0F6E56" stroke-width="0.8" stroke-linecap="round"/>
  <!-- Gills -->
  <line x1="30" y1="17" x2="27" y2="13" stroke="#9FE1CB" stroke-width="1" stroke-linecap="round"/>
  <line x1="42" y1="17" x2="45" y2="13" stroke="#9FE1CB" stroke-width="1" stroke-linecap="round"/>
</svg>
)SVG") },
    };

    auto it = kSVGs.find(static_cast<int>(state));
    if (it != kSVGs.end())
        return it->second;
    return kSVGs.at(static_cast<int>(PrintState::IDLE));
}

} // namespace PrintStatusIconSVG
} // namespace GUI
} // namespace Slic3r
