#pragma once
// PrintStatusIcon.hpp  (v4)
//
// A horizontal panel: [wxAnimationCtrl 32px] [wxStaticText debug label]
//
// Designed to sit inside create_side_tools() directly, to the right
// of the Print plate button, in the same wxBoxSizer as the other buttons.
//
// GIFs must be 32×32 px.  They live in:
//   resources/icons/print_status/status_<name>.gif   (filesystem)
//   PrintStatusIconGIF.hpp                            (embedded fallback)
// (auto-generated by generate_gif_header.py).
//
// wxAnimationCtrl handles frame timing, looping, and transparency.
// It ships with wxWidgets 2.9+ and needs no extra dependencies.


#include <wx/wx.h>
#include <wx/animate.h>
#include <functional>

namespace Slic3r {
namespace GUI {

enum class PrintState {
    IDLE,
    SLICING,
    SLICED,
    SENDING,
    PREPARE,
    RUNNING,
    PAUSE,
    FILAMENT_CHANGE,
    CALIBRATING,
    FINISH,
    FAILED,
    OFFLINE,
};

class PrintStatusIcon : public wxPanel
{
public:
    // icon_size should equal the GIF pixel size (32).
    // Pass FromDIP(32) if you want DPI scaling, but the GIF itself
    // is fixed at 32px — so only pass FromDIP(32) on 100% DPI builds
    // where DIP == physical px.  Simpler: just pass 32 directly.
    explicit PrintStatusIcon(wxWindow* parent, int icon_size = 32);
    ~PrintStatusIcon() override = default;

    // Thread-safe.  progress_pct: 0-100 or -1.
    void SetState(PrintState state, int progress_pct = -1);

    // Sets hover tooltip text.
    void SetStatusLabel(const wxString& label);

    // Called when user clicks the icon.
    void BindClickHandler(std::function<void()> handler);

private:
    void Build();
    void Apply(PrintState state, int progress_pct);

    static wxAnimation LoadAnim(PrintState state);
    static wxString    GifName (PrintState state);
    static wxString    Label   (PrintState state);
    static wxColour    LabelColour(PrintState state);

    void OnClick(wxMouseEvent& evt);

    int              m_icon_size;
    PrintState       m_state    { PrintState::OFFLINE };
    int              m_progress { -1 };

    wxAnimationCtrl* m_anim  { nullptr };
    wxStaticText*    m_text  { nullptr };

    std::function<void()> m_on_click;

    wxDECLARE_EVENT_TABLE();
};

} // namespace GUI
} // namespace Slic3r
