#pragma once
// PrintStatusIcon.hpp  (v4)
//
// A horizontal panel: [wxAnimationCtrl 32px] [wxStaticText debug label]
//
// Designed to sit inside create_side_tools() directly, to the right
// of the Print plate button, in the same wxBoxSizer as the other buttons.
//
// GIFs must be 32×32 px.  They live in:
//   resources/icons/print_status/status_<name>.gif   (filesystem)
//   PrintStatusIconGIF.hpp                            (embedded fallback)
// (auto-generated by generate_gif_header.py).
//
// wxAnimationCtrl handles frame timing, looping, and transparency.
// It ships with wxWidgets 2.9+ and needs no extra dependencies.


#include <wx/wx.h>
#include <wx/animate.h>
#include <functional>

namespace Slic3r {
namespace GUI {

enum class PrintState {
    IDLE,          // Printer is IDLE (Intended Default)
    SLICING,       // model is currently being sliced
    SLICED,        // model has been sliced into GCode
    SENDING,       // Slicer is sending the file to the printer
    PREPARE,       // Printer is setting up conditions for print
    RUNNING,       // print is in progress
    PAUSE,         // User caused a pause on the print
    FILAMENT_CHANGE, // Printer is swapping fillament or tool
    CALIBRATING,   // Printer is in calibration mode
    FINISH,        // print has finished
    FAILED,        // print has be cancelled or failed
    OFFLINE,       // connected printer not found (Note, a printer may default to this if it was power cycled and is on, but check it in Device tab and it will update)
    HEATING,       // heatbed/nozzle/chamber warming up
    LEVELING,      // bed leveling (ABL, mesh probing)
    ERROR_PAUSE,   // hardware error pause (not user-initiated, likely a warning or error state)
};

class PrintStatusIcon : public wxPanel
{
public:
    // icon_size should equal the GIF pixel size (32).
    // Pass FromDIP(32) if you want DPI scaling, but the GIF itself
    // is fixed at 32px — so only pass FromDIP(32) on 100% DPI builds
    // where DIP == physical px.  Simpler: just pass 32 directly.
    explicit PrintStatusIcon(wxWindow* parent, int icon_size = 32);
    ~PrintStatusIcon() override = default;

    // Thread-safe.  progress_pct: 0-100 or -1.
    void SetState(PrintState state, int progress_pct = -1);

    // Sets hover tooltip text.
    void SetStatusLabel(const wxString& label);

    // Called when user clicks the icon.
    void BindClickHandler(std::function<void()> handler);

    // Called when the user picks "Print Status Theme Settings…" from the
    // right-click menu (MainFrame wires this to open the Preferences dialog).
    void BindOpenPreferencesHandler(std::function<void()> handler);

    // Force a refresh of the Icon
    void ForceRefresh();

private:
    void Build();
    void Apply(PrintState state, int progress_pct);

    // Build and pop up the right-click menu: a radio list of installed
    // print-status themes plus an entry to open the preferences page.
    void ShowThemeMenu();

    static wxAnimation LoadAnim(PrintState state);
    static wxString    gif_name (PrintState state);
    static wxString    Label   (PrintState state);
    static wxColour    LabelColour(PrintState state);

    void OnClick(wxMouseEvent& evt);
    void OnRightClick(wxMouseEvent& evt);

    int              m_icon_size;
    PrintState       m_state    { PrintState::OFFLINE };
    int              m_progress { -1 };

    wxAnimationCtrl* m_anim  { nullptr };
    wxStaticText*    m_text  { nullptr };

    std::function<void()> m_on_click;
    std::function<void()> m_on_open_prefs;

    wxDECLARE_EVENT_TABLE();
};

} // namespace GUI
} // namespace Slic3r
