#!/usr/bin/env python3
"""
generate_gif_header.py
Reads all status_*.gif files from the gifs/ directory and writes
PrintStatusIconGIF.hpp — a C++ header containing the GIF bytes
as constexpr uint8_t arrays, with a GetData() function that maps
PrintState enum values to the right array.

Run this from the orca_status_v3/ directory:
    python3 generate_gif_header.py

Output: src/PrintStatusIconGIF.hpp
Re-run whenever you edit a GIF.
"""

import os

GIF_DIR = os.path.join(os.path.dirname(__file__), "gifs")
OUTPUT  = os.path.join(os.path.dirname(__file__), "src", "PrintStatusIconGIF.hpp")

STATE_MAP = {
    "status_idle":            "PrintState::IDLE",
    "status_slicing":         "PrintState::SLICING",
    "status_sliced":          "PrintState::SLICED",
    "status_sending":         "PrintState::SENDING",
    "status_prepare":         "PrintState::PREPARE",
    "status_running":         "PrintState::RUNNING",
    "status_pause":           "PrintState::PAUSE",
    "status_filament_change": "PrintState::FILAMENT_CHANGE",
    "status_calibrating":     "PrintState::CALIBRATING",
    "status_finish":          "PrintState::FINISH",
    "status_failed":          "PrintState::FAILED",
    "status_offline":         "PrintState::OFFLINE",
}

def main():
    lines = [
        "// PrintStatusIconGIF.hpp — AUTO-GENERATED by generate_gif_header.py",
        "// Do NOT edit manually. Run the script to regenerate.",
        "#pragma once",
        "#include \"PrintStatusIcon.hpp\"",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace Slic3r {",
        "namespace GUI {",
        "namespace PrintStatusIconGIF {",
        "",
    ]

    entries = []

    for filename in sorted(os.listdir(GIF_DIR)):
        if not filename.endswith(".gif"):
            continue
        stem = filename[:-4]
        if stem not in STATE_MAP:
            print(f"  WARNING: {filename} has no STATE_MAP entry — skipped")
            continue

        path = os.path.join(GIF_DIR, filename)
        with open(path, "rb") as f:
            data = f.read()

        var_name = stem.upper()  # e.g. STATUS_IDLE

        # Write the byte array
        hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
        lines.append(f"// {filename}  ({len(data)} bytes)")
        lines.append(f"static const uint8_t k_{var_name}[{len(data)}] = {{")
        # Wrap at 16 bytes per line for readability
        for i in range(0, len(data), 16):
            chunk = data[i:i+16]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
        lines.append("")

        entries.append((STATE_MAP[stem], var_name, len(data)))
        print(f"  Embedded {filename} ({len(data)} bytes) → {STATE_MAP[stem]}")

    # Write the GetData() function
    lines.append("inline const uint8_t* GetData(PrintState state, size_t& out_len)")
    lines.append("{")
    lines.append("    switch (state) {")
    for enum_val, var_name, size in entries:
        lines.append(f"    case {enum_val}:")
        lines.append(f"        out_len = {size};")
        lines.append(f"        return k_{var_name};")
    lines.append("    default:")
    lines.append("        out_len = 0;")
    lines.append("        return nullptr;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace PrintStatusIconGIF")
    lines.append("} // namespace GUI")
    lines.append("} // namespace Slic3r")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nWrote {OUTPUT}  ({len(entries)} states embedded)")

if __name__ == "__main__":
    main()
